import {StyleSheet} from 'react-native';

export const stylesBody = StyleSheet.create({
  container100: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    flexDirection: 'row',
    flexWrap: 'wrap',
    position: 'relative',
  },
  container90: {
    width: '90%',
    marginTop: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flexbetwenn: {
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  btnGreen: {
    width: '80%',
    backgroundColor: '#1ED760',
    height: 50,
    borderRadius: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 5,
  },
  btnBlack: {
    width: '80%',
    backgroundColor: '#121212',
    height: 50,
    borderRadius: 50,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 5,
    borderColor: '#fff',
    borderWidth: 1,
    padding: 10,
  },
  btnNotcolor: {
    width: '80%',
    height: 50,
    borderRadius: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
    marginTop: 5,
    padding: 10,
  },
});
